from cleanfid import fid

gt_path = "coco/val2017"

# List of datasets to test
datasets = [
    '[PATH TO THE DATASET GENERATED BY THE MODEL WITH DIFFERENT STEPS]',
]

# Compute FID score for each dataset
for dataset in datasets:
    try:
        fid_score = fid.compute_fid(dataset, gt_path)
        print(f"FID for {dataset}: {fid_score:.2f}")
    except Exception as e:
        print(f"Error computing FID for {dataset}: {str(e)}")